
all: a b c d e

.PHONY: all

a:
	g++ -O3 -std=c++11 a.cc -m64 -pthread
	./a.out

b:
	g++ -O3 -std=c++11 b.cc -m64 -pthread -o b.out
	./b.out

c:
	g++ -O3 -std=c++11 c.cc -m64 -pthread -o c.out
	./c.out

d:
	g++ -O3 -std=c++11 d.cc -m64 -pthread -o d.out
	./d.out

e:
	g++ -O3 -std=c++11 e.cc -m64 -pthread -o e.out
	./e.out
